### ISSUE TITLE
guide/built-ins/transition.md

### ISSUE THREAD

**Issue by Abdelaziz18003** [Abdelaziz18003/vuejs-docs-ar#34]

**Comment by mosaablaboune** [comment]
تم البدأ في تعريب هذه القضية

**Comment by boussadjra** [comment]
@mosaablaboune أخي مصعب إذا أنهيت تعريب هذه الصفحة يرجى رفع طلب دمج

**Comment by mosaablaboune** [comment]
آسف آسف جدا أخي ابراهيم على التأخير في التسليم، في الحقيقة قد قمت بترجمتها من مدة ونسيت عليها لذلك سأقوم بوضع بعض التعديلات وأرفعها إن شاء الله.
![image](https://github.com/Abdelaziz18003/vuejs-docs-ar/assets/51124222/631da216-ae52-4338-bcbd-bc433d219b72)

**Comment by boussadjra** [comment]
لا مشكلة أخي مصعب لقد قمت بترجمتها قبل أيام
